# Animations

animations {
    enabled = true

    # Bezier curves
    bezier = ease, 0.25, 0.1, 0.25, 1.0
    bezier = overshot, 0.05, 0.9, 0.1, 1.05
    bezier = smoothIn, 0.36, 0, 0.66, -0.56
    bezier = smoothOut, 0.36, 0, 0.66, -0.56

    # Animations
    animation = windows, 1, 5, overshot, slide
    animation = windowsOut, 1, 4, smoothOut, slide
    animation = windowsMove, 1, 4, ease, slide
    animation = border, 1, 10, default
    animation = fade, 1, 5, smoothIn
    animation = fadeDim, 1, 5, smoothIn
    animation = workspaces, 1, 6, overshot, slide
    animation = layers, 1, 4, ease, fade
}
