# Autostart

# Wallpaper daemon
exec-once = swww-daemon

# Status bar
exec-once = ~/.config/waybar/launch.sh

# Notifications
exec-once = swaync

# Clipboard manager
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Idle daemon
exec-once = hypridle

# Polkit (auth prompts)
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Set initial wallpaper + generate theme
exec-once = ~/.config/hypr/scripts/wallpaper.sh
